name: "ByteBuoy Agent: Build .NET Executables"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'test/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore .src/ByteBuoy.Agent/ByteBuoy.Agent.csproj

    - name: Build
      run: dotnet build --no-restore .src/ByteBuoy.Agent/ByteBuoy.Agent.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal .src/ByteBuoy.Agent/ByteBuoy.Agent.csproj
